---
- name: Create instance
  ec2:
    region: sa-east-1
    zone: sa-east-1a
    keypair: admin    
    instance_type: t2.small
    image: ami-af9925b2    
    vpc_subnet_id: subnet-5d698f38
    group: app
    assign_public_ip: true    
    count: 1    
    profile: midea
    wait: yes    
    instance_tags:
      Name: "blog" 
  register: ec2_instances

- name: Debug instances 
  debug: msg="{{ ec2_instances }}"


- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=120 timeout=320 state=started 
  with_items: ec2_instances.instances  

- name: Add new instance to host group
  add_host: hostname={{ item.public_ip }} groupname=ec2hosts  
  with_items: ec2_instances.instances

